DROP DATABASE IF EXISTS BOOK_RANKER;
CREATE DATABASE BOOK_RANKER
CHARACTER SET 'utf8'
COLLATE 'utf8_general_ci';
USE BOOK_RANKER;

CREATE TABLE MERCHANT(
MERCHANT_NAME VARCHAR(20) NOT NULL,
PRIMARY KEY(MERCHANT_NAME)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CATEGORY(
 CATEGORY_ID INT NOT NULL AUTO_INCREMENT,
 CATEGORY_NAME VARCHAR(100) NOT NULL UNIQUE,
 DESCRIPTION VARCHAR(100) NOT NULL,
 MERCHANT VARCHAR(50) NOT NULL,
 URL_TEMPLATE VARCHAR(200) NOT NULL UNIQUE,
 MAX_NUMBER INT NOT NULL DEFAULT 1000,
 PRIMARY KEY(CATEGORY_ID),
 FOREIGN KEY(MERCHANT) REFERENCES MERCHANT(MERCHANT_NAME)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE RANK_BOOK(
BOOK_ID INT NOT NULL AUTO_INCREMENT,
BOOK_NAME VARCHAR(100) NOT NULL,
CATEGORY_ID INT NOT NULL,
BOOK_PAGE_URL VARCHAR(500) NOT NULL,
ADD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(BOOK_ID),
FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE RANK_HISTORY(
BOOK_ID INT NOT NULL,
RANK_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
RANK INT NOT NULL,
PRIMARY KEY(BOOK_ID,RANK_DATE))ENGINE=InnoDB DEFAULT CHARSET=utf8;
